spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/movie_project_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 50
    open-in-view: false
jwt:
  secret: BnaqHVf6SlMBjYcB5bPvcXLX3LCSxvfZW09ZYPPBm1K
  access-exp: 1 #1 час
  refresh-exp: 24 # 24 часа
server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /movie-project
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
kinopoisk:
  api:
    url: https://kinopoiskapiunofficial.tech/
    key: 4d7fcf90-4f2b-43de-8390-85482c320ea3
file:
  upload-dir: uploads/
  poster-dir: posters/
movie:
  details:
    duration: 30d